spring:
  datasource:
    url: jdbc:postgresql://db.uniibtwattbeymhdzkxk.supabase.co:5432/postgres?sslmode=require
    username: postgres
    password: ZmdTCMp4cFvRiRNc
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

